# Generated by Django 4.2a1 on 2023-08-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desp', models.TextField()),
                ('job_type', models.CharField(max_length=10)),
                ('stipend', models.IntegerField()),
            ],
        ),
    ]
